# Generated by Django 2.0.8 on 2019-03-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount',
            new_name='discount_amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
