# Generated by Django 2.0.8 on 2018-11-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(blank=True, max_length=80, null=True)),
                ('user2', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
