# Generated by Django 2.0.8 on 2018-11-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_message',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='new_message',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
