# Generated by Django 2.0.8 on 2018-11-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0002_auto_20181129_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='new_message',
            field=models.BooleanField(default=True),
        ),
    ]
