# Generated by Django 2.0.8 on 2019-03-17 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180910_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='push_token',
            new_name='social_id',
        ),
    ]
