# Generated by Django 2.0.8 on 2019-03-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190317_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_pushtoken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
