# Generated by Django 2.0.8 on 2019-03-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_fcm_pushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcm_pushtoken',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
