# Generated by Django 2.0.8 on 2019-03-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coupon_history',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
