# Generated by Django 2.0.8 on 2018-11-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20181129_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='createdAt',
            field=models.DateTimeField(),
        ),
    ]
