# Generated by Django 2.0.8 on 2018-09-10 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trademark_title', models.CharField(blank=True, max_length=80, null=True)),
                ('trademark_image', models.ImageField(upload_to='')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('filed_date', models.DateTimeField(blank=True, null=True)),
                ('application_number', models.CharField(blank=True, max_length=80, null=True)),
                ('publication_number', models.CharField(blank=True, max_length=80, null=True)),
                ('publication_date', models.CharField(blank=True, max_length=80, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=80, null=True)),
                ('registration_date', models.CharField(blank=True, max_length=80, null=True)),
                ('products', models.TextField(blank=True, null=True)),
                ('product_comment', models.TextField(blank=True, null=True)),
                ('progress_status', models.CharField(blank=True, choices=[('결제 대기 중', '결제 대기 중'), ('출원 준비 중', '출원 준비 중'), ('심사 중', '심사 중'), ('출원공고', '출원공고'), ('거절 대응 중', '거절 대응 중'), ('등록', '등록'), ('갱신 대상', '갱신 대상')], max_length=80, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
