# Generated by Django 2.0.8 on 2018-10-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20180923_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
