# Generated by Django 2.0.8 on 2018-11-04 19:19

from django.db import migrations
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20181105_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='trademark_image',
        ),
        migrations.AddField(
            model_name='case',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
