# Generated by Django 2.0.8 on 2018-12-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20181105_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='identification_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
