# Generated by Django 2.0.8 on 2019-03-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20181202_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='applicantArray',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='designatedArray',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='paymentArray',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
