# Generated by Django 2.0.8 on 2019-03-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_auto_20190318_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='applicantArray',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='designatedArray',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='paymentArray',
            field=models.TextField(blank=True, null=True),
        ),
    ]
