# Generated by Django 2.0.8 on 2019-03-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20190319_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='waiting_total',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
