# Generated by Django 2.0.8 on 2019-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_case_waiting_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='waiting_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='waiting_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
