# Generated by Django 2.0.8 on 2019-03-23 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caseFiles', '0010_auto_20190323_1410'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_file', models.DateField(auto_now_add=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('possibility', models.PositiveSmallIntegerField(null=True)),
                ('examinerComment', models.TextField(blank=True, null=True)),
                ('attorneyComment', models.TextField(blank=True, null=True)),
                ('clientGiveup', models.BooleanField(default=False)),
                ('image1', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('date_of_image1', models.DateField(blank=True, null=True)),
                ('application_number1', models.CharField(blank=True, max_length=80, null=True)),
                ('image2', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('date_of_image2', models.DateField(blank=True, null=True)),
                ('application_number2', models.CharField(blank=True, max_length=80, null=True)),
                ('image3', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('date_of_image3', models.DateField(blank=True, null=True)),
                ('application_number3', models.CharField(blank=True, max_length=80, null=True)),
                ('image4', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('date_of_image4', models.DateField(blank=True, null=True)),
                ('application_number4', models.CharField(blank=True, max_length=80, null=True)),
                ('image5', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('date_of_image5', models.DateField(blank=True, null=True)),
                ('application_number5', models.CharField(blank=True, max_length=80, null=True)),
                ('casefile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='caseFiles.CaseFile')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
