# Generated by Django 2.0.8 on 2019-03-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAreports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oareport',
            name='possibility',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
