# Generated by Django 2.0.8 on 2019-03-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAreports', '0003_auto_20190323_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='oareport',
            name='applicant1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='oareport',
            name='applicant2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='oareport',
            name='applicant3',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='oareport',
            name='applicant4',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='oareport',
            name='applicant5',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
