# Generated by Django 2.0.8 on 2019-03-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAreports', '0004_auto_20190323_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='oareport',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
