# Generated by Django 2.0.8 on 2019-03-24 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20190319_1610'),
        ('searchreports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchreport',
            name='casefile',
        ),
        migrations.AddField(
            model_name='searchreport',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.Case'),
        ),
    ]
