# Generated by Django 2.0.8 on 2018-12-01 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0006_auto_20181105_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_file', models.DateField(auto_now_add=True)),
                ('file', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('file_name', models.CharField(blank=True, choices=[('위임 약정서', '위임 약정서'), ('상표 등록 출원서', '상표 등록 출원서'), ('의견 제출 통지서', '의견 제출 통지서'), ('상표 등록증', '상표 등록증'), ('기타 서류', '기타 서류')], max_length=80, null=True)),
                ('page', models.IntegerField(blank=True, max_length=50, null=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.Case')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
