# Generated by Django 2.0.8 on 2018-12-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseFiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
