# Generated by Django 2.0.8 on 2018-12-01 13:41

from django.db import migrations
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('caseFiles', '0002_auto_20181201_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casefile',
            old_name='file',
            new_name='file_page1',
        ),
        migrations.AddField(
            model_name='casefile',
            name='file_page2',
            field=imagekit.models.fields.ProcessedImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
