# Generated by Django 2.0.8 on 2018-12-01 13:45

from django.db import migrations
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('caseFiles', '0003_auto_20181201_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casefile',
            name='page',
        ),
        migrations.AddField(
            model_name='casefile',
            name='file_page3',
            field=imagekit.models.fields.ProcessedImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casefile',
            name='file_page4',
            field=imagekit.models.fields.ProcessedImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casefile',
            name='file_page5',
            field=imagekit.models.fields.ProcessedImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
