# Generated by Django 2.0.8 on 2018-12-01 13:49

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('caseFiles', '0004_auto_20181201_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='file_page2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='file_page3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='file_page4',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='file_page5',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
    ]
