# Generated by Django 2.0.8 on 2019-03-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseFiles', '0005_auto_20181201_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='file_pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
