# Generated by Django 2.0.8 on 2019-03-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseFiles', '0006_casefile_file_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casefile',
            name='file_page1',
        ),
        migrations.RemoveField(
            model_name='casefile',
            name='file_page2',
        ),
        migrations.RemoveField(
            model_name='casefile',
            name='file_page3',
        ),
        migrations.RemoveField(
            model_name='casefile',
            name='file_page4',
        ),
        migrations.RemoveField(
            model_name='casefile',
            name='file_page5',
        ),
    ]
