# Generated by Django 2.0.8 on 2019-03-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseFiles', '0009_casefile_expiredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='file_name',
            field=models.CharField(blank=True, choices=[('위임 약정서', '위임 약정서'), ('상표 등록 출원서', '상표 등록 출원서'), ('의견 제출 통지서', '의견 제출 통지서'), ('등록 결정서', '등록 결정서'), ('거절 결정서', '거절 결정서'), ('상표 등록증', '상표 등록증'), ('기타 서류', '기타 서류')], max_length=80, null=True),
        ),
    ]
